# Generated by Django 4.0.6 on 2022-07-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
                ('cohort', models.CharField(max_length=64)),
                ('_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.user')),
            ],
        ),
    ]
