# Generated by Django 3.2 on 2022-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('card', 'user')},
        ),
    ]
