# Generated by Django 4.0.6 on 2022-07-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='likes',
            field=models.ManyToManyField(through='cards.Like', to='cards.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.user'),
        ),
    ]
